# Generated by Django 5.0.1 on 2024-02-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='anons',
            new_name='intro',
        ),
    ]
